services:
  mysql:
    platform: linux/x86_64 # Tips: mysql -> ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries
    image: mysql:8.3.0 # https://hub.docker.com/_/mysql
    command: --default-authentication-plugin=mysql_native_password # 8.4.1 -> unknown variable
    volumes:
      - mysql:/var/lib/mysql
    env_file: .env
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "mysql"]
      interval: 5s # <- 30s
      timeout: 10s # <- 30s
      retries: 10 # <- 3
  pg:
    image: postgres:17.6-alpine # https://hub.docker.com/_/postgres
    volumes:
      - pg:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s # <- 30s
      timeout: 10s # <- 30s
      retries: 10 # <- 3
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes:
      - .:/workdir:cached
      - bundle_ruby_3.4:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - mysql
      - pg
  web:
    image: nginx:1.27.5-alpine # https://hub.docker.com/_/nginx
    volumes:
      - ./ecs/web/nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./ecs/web/nginx/conf.d/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./public:/usr/share/nginx/html
    command: >
      /bin/sh -c "
        envsubst '$$NGINX_WORKER_PROCESSES $$NGINX_WORKER_RLIMIT_NOFILE $$NGINX_WORKER_CONNECTIONS $$NGINX_SET_REAL_IP_FROM $$NGINX_REAL_IP_HEADER' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf &&
        envsubst '$$NGINX_PROXY_PASS' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf &&
        nginx -g 'daemon off;'"
    environment:
      NGINX_WORKER_PROCESSES: "auto" # 最大値: vCPUの数 or auto = 16と仮定して
      NGINX_WORKER_RLIMIT_NOFILE: 32768 # 最大値: 524288(cat /proc/sys/fs/file-max) / NGINX_WORKER_PROCESSES
      NGINX_WORKER_CONNECTIONS: 8192 # 最大値: NGINX_WORKER_RLIMIT_NOFILE / 4
      NGINX_SET_REAL_IP_FROM: "172.31.0.0/16" # <- ELB
      NGINX_REAL_IP_HEADER: "X-Forwarded-For" # <- ELB
      NGINX_PROXY_PASS: "http://app:3000"
    ports:
      - 80:80
    depends_on:
      - app
  job:
    build: .
    command: bundle exec rails jobs:work
    volumes:
      - .:/workdir
      - bundle_ruby_3.4:/usr/local/bundle
    depends_on:
      mysql:
        condition: service_healthy
      pg:
        condition: service_healthy
  schemaspy:
    build: schemaspy/
    volumes:
      - ./schemaspy:/workdir/schemaspy
    depends_on:
      - mysql
      - pg
volumes:
  mysql:
  pg:
  bundle_ruby_3.4:
