services:
  mysql:
    platform: linux/x86_64 # Tips: mysql -> ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries
    image: mysql:8.3.0 # https://hub.docker.com/_/mysql
    command: --default-authentication-plugin=mysql_native_password # 8.4.1 -> unknown variable
    volumes:
      - mysql:/var/lib/mysql
    env_file: .env
    environment:
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
  mariadb:
    image: mariadb:12.1.2 # https://hub.docker.com/_/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file: .env
    environment:
      TZ: Asia/Tokyo
    ports:
      - 4306:3306
  pg:
    image: postgres:18.1-alpine3.22 # https://hub.docker.com/_/postgres
    volumes:
      - pg_18:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5432:5432
  app:
    build: .
    command: >
      /bin/sh -c "
        gem install bundler -v 2.7.2 && bundle install -j4 --retry=3 &&
        yarn install &&
        rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'
      "
    stdin_open: true
    tty: true
    volumes:
      - .:/workdir:cached
      - bundle_ruby_3.4:/usr/local/bundle
      - node_modules:/workdir/node_modules
    ports:
      - 3000:3000
    depends_on:
      - mysql
      - mariadb
      - pg
  web:
    image: nginx:1.27.5-alpine # https://hub.docker.com/_/nginx
    volumes:
      - ./ecs/web/nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./ecs/web/nginx/conf.d/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./public:/usr/share/nginx/html
    command: >
      /bin/sh -c "
        envsubst '$$NGINX_WORKER_PROCESSES $$NGINX_WORKER_RLIMIT_NOFILE $$NGINX_WORKER_CONNECTIONS $$NGINX_SET_REAL_IP_FROM $$NGINX_REAL_IP_HEADER' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf &&
        envsubst '$$NGINX_PROXY_PASS' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf &&
        nginx -g 'daemon off;'
      "
    environment:
      NGINX_WORKER_PROCESSES: "auto" # 最大値: vCPUの数 or auto = 16と仮定して
      NGINX_WORKER_RLIMIT_NOFILE: 32768 # 最大値: 524288(cat /proc/sys/fs/file-max) / NGINX_WORKER_PROCESSES
      NGINX_WORKER_CONNECTIONS: 8192 # 最大値: NGINX_WORKER_RLIMIT_NOFILE / 4
      NGINX_SET_REAL_IP_FROM: "172.31.0.0/16" # <- ELB
      NGINX_REAL_IP_HEADER: "X-Forwarded-For" # <- ELB
      NGINX_PROXY_PASS: "http://app:3000"
    ports:
      - 80:80
    depends_on:
      - app
  job:
    build: .
    command: >
      /bin/sh -c "
        gem install bundler -v 2.7.2 && bundle install -j4 --retry=3 &&
        bundle exec rails jobs:work
      "
    volumes:
      - .:/workdir
      - bundle_ruby_3.4:/usr/local/bundle
    depends_on:
      - app
      - mysql
      - mariadb
      - pg
  schemaspy:
    build: schemaspy/
    volumes:
      - ./schemaspy:/workdir/schemaspy
    depends_on:
      - mysql
      - mariadb
      - pg
volumes:
  mysql:
  mariadb:
  pg_18:
  bundle_ruby_3.4:
  node_modules:
