# APIのみモード  NOTE: Railsのフロントを使用しない場合はtrue
api_only_mode: true # NOTE: APIのみ開発する

# 言語選択
default_locale: :ja
# default_locale: :en
locales:
  en: 'English'
  ja: '日本語'

# Devise Token Auth
confirmation_success_url_not: '/auth/confirmation_success.html?not'
confirmation_success_url_bad: '/auth/confirmation_success.html?bad'
confirmation_error_url_not: '/auth/confirmation_error.html?not'
confirmation_error_url_bad: '/auth/confirmation_error.html?bad'
unlock_success_url_not: '/auth/unlock_success.html?not'
unlock_success_url_bad: '/auth/unlock_success.html?bad'
unlock_error_url_not: '/auth/unlock_error.html?not'
unlock_error_url_bad: '/auth/unlock_error.html?bad'
reset_password_error_url_not: '/auth/reset_password_error.html?not'
reset_password_error_url_bad: '/auth/reset_password_error.html?bad'

## ユーザー
# メールアドレス確認URLの有効期限（単位：時間）
confirm_within_hours: 24
# パスワード再設定URLの有効期限（単位：時間）
reset_password_within_hours: 24
# アカウントロックの有効期間（単位：時間）
unlock_in_hours: 1
# アカウント削除の猶予期間（単位：日）
user_destroy_schedule_days: 7
# アカウント削除完了メール送信(true or false)  NOTE: 「rails user:destroy[false]」をcronで実行（メール送信する場合、夜間は避けた方が良い）
sendmail_destroy_completed: true
# 氏名の最小・最大文字数
user_name_minimum: 1
user_name_maximum: 32

## お知らせ
# 一覧のデフォルト最大表示件数
default_infomations_limit: 25

## スペース
# 公開スペース使用可否  ※後からfalseに変更しても作成済みの公開スペースは表示されます。
enable_public_space: false # NOTE: 非公開のみ
default_private_space: true
# スペース削除の猶予期間（単位：日）
space_destroy_schedule_days: 14
# 一覧のデフォルト最大表示件数
default_spaces_limit: 25
# コードの文字数
space_code_length: 8
# 名称の最小・最大文字数
space_name_minimum: 3
space_name_maximum: 128
# 説明の最大文字数
space_description_maximum: 4096

## 招待URL
# 招待削除の猶予期間（単位：日）
invitation_destroy_schedule_days: 7
# 一覧のデフォルト最大表示件数
default_invitations_limit: 25
# ドメインの最大件数
invitation_domains_max_count: 10
# ドメインの最大文字数
invitation_domain_maximum: 253
# メモの最大文字数
invitation_memo_maximum: 64

## メンバー
# 一覧のデフォルト最大表示件数
default_members_limit: 25
job_members_limit: 1000
# メールアドレスの最大件数
member_emails_max_count: 100

## ダウンロード
# 一覧のデフォルト最大表示件数
default_downloads_limit: 25
# ダウンロード削除の猶予期間（単位：日）
download_destroy_schedule_days: 7

## タスク
# 一覧のデフォルト最大表示件数
default_tasks_limit: 25
# 優先度の並び順
priority_order:
  high: 1   # 高
  middle: 2 # 中
  low: 3    # 低
  none: 9   # 未設定
# タイトルの最大文字数
task_title_maximum: 128
# 概要の最大文字数
task_summary_maximum: 10240
# 前提の最大文字数
task_premise_maximum: 10240
# 手順の最大文字数
task_process_maximum: 10240
# 周期の最大件数
task_cycles_max_count: 5
# 担当割当の最大件数
task_assigne_users_max_count: 10
# イベントの最大月数
task_events_max_month_count: 4

## タスクイベント
# メモの最大文字数
task_event_memo_maximum: 10240

## Slackユーザー
# SlackメンバーIDの最小・最大文字数
slack_user_memberid_minimum: 8
slack_user_memberid_maximum: 16 # NOTE: 現在11桁っぽいけど余裕を持て

## 通知設定
# (Slack)ドメイン名（サブドメイン）の最大文字数
slack_domain_name_maximum: 32
# (Slack)Webhook URLの最大文字数
slack_webhook_url_maximum: 128
# (Slack)メンションの最大文字数
slack_mention_maximum: 64
# (開始確認)デフォルト開始時間/完了通知/必須
default_start_notice_start_hour: 10
default_start_notice_completed: true
default_start_notice_required: false
# (翌営業日・終了確認)デフォルト開始時間/完了通知/必須
default_next_notice_start_hour: 17
default_next_notice_completed: true
default_next_notice_required: false

## 通知履歴
# 一覧のデフォルト最大表示件数
default_send_histories_limit: 25
