debug: true
server_env: 'development'
base_domain: <%= ENV['BASE_DOMAIN'] %>
cors_origins: '*'
base_image_url: <%= ENV['BASE_IMAGE_URL'].presence || "'https://#{ENV['BASE_DOMAIN']}'" %>
front_url: 'http://localhost:5000'
logo_image_url: 'https://task.nightonly.com/logo.png' # NOTE: どこからでもアクセスできるURL
redirect_whitelist: <%= eval(ENV['REDIRECT_WHITELIST'].presence || '[]') %>
default_confirm_success_url: null
default_password_reset_url: null
default_unlock_success_url: null
mailer_from:
  name: '%{app_name}'
  email: 'noreply@localhost'
exception_notifier:
  email_enabled: true
  email_config:
    email_prefix: '[WARNING](development)'
    sender_address: 'noreply@localhost'
    exception_recipients: ['warning']
  slack_enabled: false
  slack_config:
    webhook_url: 'https://hooks.slack.com/services/xxxxxxxx'
    additional_parameters:
      color: 'good'
