debug: false
env_name: null
base_domain: 'localhost.test'
base_image_url: 'http://localhost.test'
front_url: 'http://front.localhost.test'
logo_image_url: 'https://front.localhost.test/logo.png'
redirect_whitelist: ['http://front.localhost.test/*']
default_confirm_success_url: null
default_password_reset_url: null
default_unlock_success_url: null
mailer_from:
  name: '%{app_name}'
  email: 'noreply@localhost.test'
exception_notifier:
  email_enabled: false
  slack_enabled: false

## ユーザー
# ユーザー名の最小・最大文字数
user_name_minimum: 2  # NOTE: 2以上、(7+5?)以下 = "admin(#{n})", "user(#{n})"
user_name_maximum: 12 # NOTE: (7+5?)以上

## お知らせ
# 一覧のデフォルト最大表示件数
default_infomations_limit: 4 # NOTE: 高速化の為（下記の合計値と一致）
test_infomations_count:
  all_forever: 1
  all_future: 1
  user_forever: 1
  user_future: 1

## スペース
# 一覧のデフォルト最大表示件数
default_spaces_limit: 4 # NOTE: 高速化の為（下記の合計値と一致）
test_spaces_count:
  public_admin: 1
  public_none: 1
  private_admin: 1
  private_reader: 1
# コードの文字数
# space_code_length: 8
# 名称の最小・最大文字数
space_name_minimum: 2  # NOTE: 2以上、(7+8?)以下 = "space(#{n})""
space_name_maximum: 15 # NOTE: (7+8?)以上
# 説明の最大文字数
space_description_maximum: 22 # NOTE: (13+8?)以上 = "description(#{n})"

## 招待URL
# 一覧のデフォルト最大表示件数
default_invitations_limit: 4 # NOTE: 高速化の為（下記の合計値と一致）
test_invitations_count:
  active: 1
  expired: 1
  deleted: 1
  email_joined: 1
# ドメインの最大件数
invitation_domains_max_count: 2 # NOTE: 2以上
# ドメインの最大文字数
# invitation_domain_maximum: 253
# メモの最大文字数
invitation_memo_maximum: 14 # NOTE: (6+8?)以上 = "memo(#{n})"

## メンバー
# 一覧のデフォルト最大表示件数
default_members_limit: 4 # NOTE: 高速化の為（下記の合計値+1と一致）
test_members_count:
  admin: 1
  writer: 1
  reader: 1
job_members_limit: 2
# メールアドレスの最大件数
member_emails_max_count: 3 # NOTE: テストパターンに合わせる

## ダウンロード
# 一覧のデフォルト最大表示件数
default_downloads_limit: 5 # NOTE: 高速化の為（下記の合計値と一致）
test_downloads_count:
  waiting: 1
  processing: 1
  success: 1
  failure: 1
  downloaded: 1

## タスク
# 一覧のデフォルト最大表示件数
default_tasks_limit: 4 # NOTE: 高速化の為（下記の合計値と一致）
test_tasks_count:
  high: 1
  middle: 1
  low: 1
  none: 1
# タイトルの最大文字数
task_title_maximum: 14 # NOTE: (6+8?)以上 = "task(#{n})"
# 概要の最大文字数
task_summary_maximum: 17 # NOTE: (6+8?+3)以上 = "#{title}の概要"
# 前提の最大文字数
task_premise_maximum: 17 # NOTE: (6+8?+3)以上 = "#{title}の前提"
# 手順の最大文字数
task_process_maximum: 17 # NOTE: (6+8?+3)以上 = "#{title}の手順"
# 周期の最大件数
task_cycles_max_count: 3 # NOTE: 日/営業日/週
# イベントの最大月数
# task_events_max_month_count: 4

## タスクイベント
# メモの最大文字数
task_event_memo_maximum: 14 # NOTE: (6+8?)以上 = "memo(#{n})"

## Slackユーザー
# SlackのメンバーIDの最大文字数
# slack_user_memberid_minimum: 11
slack_user_memberid_maximum: 16 # NOTE: Faker::Number.hexadecimal(digits: 11).upcase

## 通知設定
# [Slack]ドメイン名（サブドメイン）の最大文字数
# slack_domain_name_maximum: 32
# [Slack]Webhook URLの最大文字数
slack_webhook_url_maximum: 64 # NOTE: Faker::Internet.url
# [Slack]メンションの最大文字数
slack_mention_maximum: 8 # NOTE: '!here'
# [開始確認]デフォルト開始時間/完了通知/必須
# default_start_notice_start_hour: 10
# default_start_notice_completed: true
# default_start_notice_required: false
# [翌営業日・終了確認]デフォルト開始時間/完了通知/必須
# default_next_notice_start_hour: 17
# default_next_notice_completed: true
# default_next_notice_required: false

## 通知履歴
# 一覧のデフォルト最大表示件数
default_send_histories_limit: 2
